# Example of specs to build stage tarballs
# MARK Devkit Specifications
version: "1.0"

jobs:
- name: stage3-arm64bit
  source:
    type: http
    uri: "https://mark-os.macaronios.org/mark-stages-mark31/arm64/generic_aram64/{{ .Values.coffnix_stage3_seed_date }}/stage3-generic_arm64-mark-31-{{ .Values.coffnix_stage3_seed_date }}.tar.xz"
    target: /workspace/sourcer/{{ .Values.release }}/{{ .Values.arch }}/{{ .Values.subarch }}/stage3-latest-{{ now | date "2006-01-02" }}.tar.xz
  output:
    type: file
    name: stage3-{{ .Values.arch }}-{{ .Values.subarch }}-{{ .Values.release }}{{- if .Values.extras }}+{{- end }}{{ join "+" .Values.extras }}-{{ now | date "2006-01-02" }}.tar.xz
    dir: '../../output/mark-31/{{ .Values.release }}/{{ .Values.arch }}/{{ .Values.subarch }}/{{ now | date "2006-01-02" }}/'

  options:
    branch: "mark-31"
    release: "mark-31"
    arch: arm-64bit
    subarch: arm64_generic
    sync_base_url: https://github.com/macaroni-os/{repo}
    extras:
      - minimal
    # Keep date as string to avoid automatic convertion in timestamp
    coffnix_stage3_seed_date: "2025-08-09"

  environments:
    - key: "SHELL"
      value: "/bin/bash"
    - key: "MAKEOPTS"
      value: "-j9"
    - key: "FEATURES"
      value: "-pid-sandbox -network-sandbox -sandbox -usersandbox -ipc-sandbox -selinux -sesandbox"
    - key: "EMERGE_WARNING_DELAY"
      value: "0"
    - key: "CLEAN_DELAY"
      value: "0"
    - key: "EBEEP_IGNORE"
      value: "0"
    - key: "EPAUSE_IGNORE"
      value: "0"
    - key: "CONFIG_PROTECT"
      value: "-* /etc/locale.gen /etc/ego.conf"
    - key: "UNINSTALL_IGNORE"
      value: "/etc/portage/*"
    - key: "DISTDIR"
      value: "/var/cache/portage/distfiles"
    - key: "PKGDIR"
      value: "/var/tmp/cache/package"
    - key: "eopts"
      value: "--jobs=4 --load-average=4 --keep-going=n --usepkg --with-bdeps=y --buildpkg"
    - key: "GENTOO_MIRRORS"
      value: "https://distfiles.macaronios.org https://dl.macaronios.org/repos/distfiles"


  workspacedir: /workspace
  chroot_binds:
    - source: /workspace/package
      target: /var/tmp/cache/package
    - source: /workspace/distfiles
      target: /var/cache/portage/distfiles
    #- source: /workspace/meta-repo
    #  target: /var/git/meta-repo

  hooks_basedir: ../hooks
  # Define the list of the targets
  # scripts to run over the chroot.
  hooks_files:
    - steps/ego.yml
    - steps/prepare-chroot.yml
    - targets/prelude.yml
    - targets/stage3.yml
    - steps/stage.yml
